"""
Backtest API Service - 설정
"""
import os

# === 공유 전략 설정 import ===
from strategy_config import (
    STRATEGY_NAME,
    COINS,
    TIMEFRAMES,
    V12_5_MIN_ENTRY_PRICE,
    V12_5_MIN_ENTRY_PRICE_LATE,
    V12_5_EARLY_CUTOFF_MINUTES,
    V12_5_COOLDOWN_SECONDS,
    V12_5_MAX_SPREAD,
    BET_AMOUNT,
    MIN_LIQUIDITY,
)

# === Crossing 전략 설정 ===
# crossing (V1): 5회 제한, 14:30 cutoff
CROSSING_FIRST_BET = 10.0
CROSSING_SUBSEQUENT_BET = 20.0
CROSSING_MAX_COUNT = 5
CROSSING_COUNT_START_SECONDS = 60
CROSSING_CUTOFF_SECONDS = 870
CROSSING_MIN_ENTRY_PRICE = 0.10
CROSSING_MAX_ENTRY_PRICE = 0.90

# crossing_v2: 무제한, 14분 cutoff
CROSSING_V2_CUTOFF_SECONDS = 840

# === DB 설정 ===
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = int(os.getenv("DB_PORT", 5435))
DB_NAME = os.getenv("DB_NAME", "paper_trade")
DB_USER = os.getenv("DB_USER", "paper")
DB_PASSWORD = os.getenv("DB_PASSWORD", "papertrade")

# Re-export for convenience
__all__ = [
    'STRATEGY_NAME', 'COINS', 'TIMEFRAMES',
    'V12_5_MIN_ENTRY_PRICE', 'V12_5_MIN_ENTRY_PRICE_LATE',
    'V12_5_EARLY_CUTOFF_MINUTES', 'V12_5_COOLDOWN_SECONDS', 'V12_5_MAX_SPREAD',
    'BET_AMOUNT', 'MIN_LIQUIDITY',
    'CROSSING_FIRST_BET', 'CROSSING_SUBSEQUENT_BET',
    'CROSSING_MAX_COUNT', 'CROSSING_COUNT_START_SECONDS', 'CROSSING_CUTOFF_SECONDS',
    'CROSSING_MIN_ENTRY_PRICE', 'CROSSING_MAX_ENTRY_PRICE',
    'CROSSING_V2_CUTOFF_SECONDS',
    'DB_HOST', 'DB_PORT', 'DB_NAME', 'DB_USER', 'DB_PASSWORD',
]
